### ISSUE TITLE
Get video upload working

### ISSUE THREAD

**Issue by caleb-bb** [caleb-bb/fyoog#1]
We want to be able to upload videos, have them hosted on S3, and then watchable from the page.

- [ ] Build a "stage" where users can go to upload videos. The stage should show all videos uploaded by that user and have options for deleting them and uploading more. Users are "on stage" here. References #2 
- [ ] Connect to S3 and make it possible to upload videos to a bucket. References #3 
- [ ]  Make videos watchable.
